[Outlook] (sensitivity label) Create sample
OfficeDev/Office-Add-in-samples pull request #508
Opened 2023-03-31 02:23 UTC by samantharamon

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                              |
| New feature?    | yes                           |
| New sample?     | yes                             |
| Related issues? | N/A |

## What's in this Pull Request?

This sample uses the sensitivity label API in an event-based add-in to verify and apply the **Highly Confidential** sensitivity label to outgoing messages that contain at least one attachment or a recipient who's a member of the fictitious Fabrikam legal team. When the **Highly Confidential** label is applied, a fictitious legal hold account is added to the **Bcc** field of the message.

## Guidance

See above.

2023-04-04 17:45 UTC, ElizabethSamuel-MSFT commented on README.md
> +| [Verify the sensitivity label of a message (preview)](Samples/outlook-check-item-categories/) | Uses the sensitivity label API in an event-based add-in to verify and apply the **Highly Confidential
```suggestion
| [Verify the sensitivity label of a message (preview)](Samples/outlook-verify-sensitivity-label/) | Uses the sensitivity label API in an event-based add-in to verify and apply the **Highly Confidential** sensitivity label to applicable outgoing messages. |
```

2023-04-04 17:45 UTC, ElizabethSamuel-MSFT commented on Samples/outlook-verify-sensitivity-label/README.md
> +    event.completed({ allowEvent: false, errorMessage: "Due to the contents of your message, the sensitivity label has been set to Highly Confidential and the Legal Hold account has been added to the
Do we know if `\n` renders correctly on Mac?

2023-04-17 20:05 UTC, davidchesnut requested changes
Looks great! Please take a look at a few comments I had. Thanks!

2023-04-17 20:05 UTC, davidchesnut commented on Samples/outlook-verify-sensitivity-label/README.md
> +This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information, see the [Code of Conduct FAQ](https://opensource.microsoft
```suggestion
This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information, see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

<img src="https://pnptelemetry.azurewebsites.net/pnp-officeaddins/samples/outlook-verify-sensitivity-label" />
```

2023-04-17 20:35 UTC, samantharamon commented on Samples/outlook-verify-sensitivity-label/README.md
> +This sample uses the sensitivity label API in an event-based add-in to verify and apply the **Highly Confidential** sensitivity label to outgoing messages that contain at least one attachment or a re
Thanks for catching this. Yes, this should be lowercase.

2023-04-17 20:35 UTC, samantharamon commented on Samples/outlook-verify-sensitivity-label/README.md
> +    The sensitivity label of the message is set to **Highly Confidential** and the **legalhold@fabrikam.com** account is added to the **Bcc** field. A Smart Alerts dialog appears that reads, "Due to
I tested this with just an attachment and confirmed that the legalhold@fabrikam.com account was added to the Bcc field. If you get a chance, could you try testing that scenario again? Let me know if you're still able to replicate the issue. Thanks!

2023-04-17 23:04 UTC, samantharamon commented on Samples/outlook-verify-sensitivity-label/README.md
> +    The sensitivity label of the message is set to **Highly Confidential** and the **legalhold@fabrikam.com** account is added to the **Bcc** field. A Smart Alerts dialog appears that reads, "Due to
Thanks for troubleshooting this and finding the fix, @davidchesnut! The `associate` calls have now been moved to `Office.onReady`.

2023-04-17 23:21 UTC, davidchesnut approved these changes
Looks great! Thanks!

2023-04-17 23:21 UTC, davidchesnut commented on Samples/outlook-verify-sensitivity-label/README.md
> +    The sensitivity label of the message is set to **Highly Confidential** and the **legalhold@fabrikam.com** account is added to the **Bcc** field. A Smart Alerts dialog appears that reads, "Due to
Fixed now, thanks!

2023-04-18 17:47 UTC, ElizabethSamuel-MSFT approved these changes

2023-04-18 17:47 UTC, ElizabethSamuel-MSFT commented on Samples/outlook-verify-sensitivity-label/README.md
> +  createdDate: 03/27/2023 10:00:00 AM
```suggestion
  createdDate: 04/18/2023 10:00:00 AM
```

2023-04-18 17:47 UTC, ElizabethSamuel-MSFT commented on Samples/outlook-verify-sensitivity-label/README.md
> +|1.0|March 27, 2023|Initial release|
```suggestion
|1.0|April 18, 2023|Initial release|
```

2023-04-18 17:57 UTC, merged