[Outlook] - NAA sample with IE fallback
OfficeDev/Office-Add-in-samples pull request #860
Opened 2024-09-30 06:45 UTC by codexeon

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                              |
| New feature?    | no                              |
| New sample?     | yes                              |
| Related issues? | NA |

## What's in this Pull Request?

This adds a new sample that is similar to Outlook-Add-in-SSO-NAA, but has support for Internet Explorer (IE) fallback. IE fallback sample may not be for every app developer as it adds overhead of supporting multiple auth libraries and polyfills, but can be used as a reference if your add-in must support IE environments.

2024-09-30 18:05 UTC, AlexJerabek requested changes
The sample looks good. This is mostly a copy edit on the readme. Has someone else tested the IE11 fallback path?

2024-09-30 18:05 UTC, AlexJerabek commented on Samples/auth/Outlook-Add-in-SSO-NAA-IE/src/taskpane/fallback/dialog.html
> +    <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.debug.js"></script>
Should this not be the debug version?
```suggestion
    <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>
```

2024-10-01 05:43 UTC, codexeon commented on Samples/auth/Outlook-Add-in-SSO-NAA-IE/README.md
> +1. Sign in with the **_admin_** credentials to your Microsoft 365 tenancy. For example, **MyName@contoso.onmicrosoft.com**.
not sure I understand the comment, but this matches existing Outlook-Add-in-SSO-NAA sample. It doesn't require admin to create the registration, but it does require it to consent to files.read scope.

2024-10-01 05:45 UTC, codexeon commented on Samples/auth/Outlook-Add-in-SSO-NAA-IE/README.md
> +   - Set **Name** to `Outlook-Add-in-SSO-NAA`.
it shouldn't be a problem as it has a unique id, but I updated the name.

2024-10-01 16:39 UTC, AlexJerabek commented on Samples/auth/Outlook-Add-in-SSO-NAA-IE/README.md
> +1. Sign in with the **_admin_** credentials to your Microsoft 365 tenancy. For example, **MyName@contoso.onmicrosoft.com**.
I read this sentence as "Sign in with your admin account (e.g.: MyName@contoso.onmicrosoft.com)." I'm not sure why the email address help clarify anything. Guess this is more of a general question for @davidchesnut across all the samples. Please leave it as is.

2024-10-01 16:41 UTC, AlexJerabek approved these changes
Thanks for making those changes. Approving with one more suggestion.

2024-10-01 16:41 UTC, AlexJerabek commented on Samples/auth/Outlook-Add-in-SSO-NAA-IE/assets/sample.json
> +    "name": "outlook-add-in-sso-naa",
```suggestion
    "name": "outlook-add-in-sso-naa-ie",
```

2024-10-01 17:45 UTC, merged