Merge dev into main
OfficeDev/Office-Add-in-samples pull request #908
Opened 2024-12-19 03:02 UTC by hermanwenhe

Merge dev into main for Dev Kit release

2024-12-20 18:46 UTC, Rick-Kirkham requested changes

2024-12-23 02:41 UTC, hermanwenhe commented on Samples/excel-add-in-shape-dashboard/src/taskpane/taskpane.html
> +        <p class="sampleSubTitle">Add event handlers to the dashboard. These handlers will update the dashboard information when it is selected or unselected.</p>
Updated. Please check.

2024-12-23 07:39 UTC, Rick-Kirkham requested changes

2024-12-23 07:39 UTC, Rick-Kirkham commented on Samples/excel-add-in-shape-dashboard/src/taskpane/taskpane.html
> +        <p class="sampleSubTitle">Add onActivate/onDeactivated event handlers to the dashboard. These handlers will update the dashboard information when the dashboard is selected or unselected.</p>
I finally got this to work. This is what I think it should say. 

```suggestion
        <p class="sampleSubTitle">While a cell outside the dashboard is selected, click the button to add onActivated/onDeactivated event handlers to the dashboard. Then click any shape on the dashboard and the type of information displayed changes. Then click any cell outside the dashboard and the information changes back. </p>
```

2024-12-23 08:05 UTC, merged